[package]
name = "actix-web-middleware-https"
version = "0.1.0"
authors = ["Peter Trotman <petertrotman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
